src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    private ?string $plainPassword = null;

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    #[ORM\Column(length: 255)]
    private ?string $Pseudo = null;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column]
    private ?int $UserId = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ResetPasswordToken::class)]
    private Collection $Id;

    public function __construct()
    {
        $this->Id = new ArrayCollection();
    }

    /**
     * @return bool
     */
    public function isIsVerified(): bool
    {
        return $this->is_verified;
    }

    /**
     * @param bool $is_verified
     */
    public function setIsVerified(bool $is_verified): void
    {
        $this->is_verified = $is_verified;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): static
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->UserId;
    }

    public function setUserId(int $UserId): static
    {
        $this->UserId = $UserId;

        return $this;
    }

    public function addId(ResetPasswordToken $id): static
    {
        if (!$this->Id->contains($id)) {
            $this->Id->add($id);
            $id->setUser($this);
        }

        return $this;
    }

    public function removeId(ResetPasswordToken $id): static
    {
        if ($this->Id->removeElement($id)) {
            // set the owning side to null (unless already changed)
            if ($id->getUser() === $this) {
                $id->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\FiguresRepository;

class DefaultController extends AbstractController
{
    #[Route('/accueil', name: 'app_default')]
    public function index(FiguresRepository $figuresRepository): Response
    {
        $latestFigures = $figuresRepository->findLatestFigures(10);
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'latestFigures' => $latestFigures,
        ]);
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SnowFlow{% endblock %}

{% block body %}
{% for flashMessage in app.flashes('success') %}
    <div class="alert alert-success">
        {{ flashMessage }}
    </div>
{% endfor %}

{% for flashMessage in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ flashMessage }}
    </div>
{% endfor %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        .webmadewell {
            background-color: white;
        }
        body {
            margin: 0;
        }
        

        h1 {
            font-weight: 500;
        }
        h2 {
            font-weight: 400;
        }
        
    </style>
    <div class="sample-image" style="background-image: url('http://webmadewell.com/wp-content/uploads/2018/01/img-bg-sample-parallax-header.jpg'); background-size: cover; background-position: center; height: 100vh; text-align: center;">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-md-8 offset-md-2">
                <h1 class="text-white">Bienvenue sur SnowTrick</h1>
                <h2 class="text-white">Le blog spécialisé en figures</h2>
                <a href="#figures-section" class="mt-3"><i class="fa-solid fa-arrow-down fa-3x"style="color:white   "></i></a>
            </div>
        </div>
    </div>
</div>

<section id="figures-section" class="sample-section-wrap mt-5" style="background-color: white;">
<div style="margin-top: 150px; text-align: center;" ><h1>Liste des figures</h1></div>
    <div class="sample-section" >
        <div class="container">
            <div class="row row-cols-1 row-cols-md-5 g-4">
                {% for figure in latestFigures %}
                    <div class="col">
                        <div class="card m-3">
                            {% if figure.illustrations is not empty %}
                                <img src="{{ asset('uploads/figures/' ~ figure.illustrations[0]) }}" class="card-img-top" alt="Illustration">
                            {% endif %}
                            <div class="card-body">
                                <h5><a href="{{ path('app_figure_detail', {'id': figure.id}) }}">{{ figure.name }}</a></h5>
                                <div class="btn-group">
                                    {% if app.user %}
                                        {% if figure.userId == app.user.id %}
                                            <a href="{{ path('modifier_figure', {'id': figure.id}) }}" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-pen"></i></a>
                                            <a href="{{ path('supprimer_figure', {'id': figure.id}) }}" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-trash"></i></a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if loop.index % 5 == 0 %}
                </div>
                <div class="row row-cols-1 row-cols-md-5 g-4">
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>




    </div>
</div>

    </div>
    <script>
        function parallax_height() {
            var scroll_top = $(this).scrollTop();
            var sample_section_top = $(".sample-section").offset().top;
            var header_height = $(".sample-header-section").outerHeight();
            $(".sample-section").css({ "margin-top": header_height });
            $(".sample-header").css({ height: header_height - scroll_top });
        }
        parallax_height();
        $(window).scroll(function() {
            parallax_height();
        });
        $(window).resize(function() {
            parallax_height();
        });
    </script>

{% endblock %}