src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $figure_id = null;




    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "user_id", referencedColumnName: "id")]
    private User $user;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;
    #[ORM\ManyToOne(targetEntity: Figures::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(name: 'figure_id', referencedColumnName: 'id')]
    private Figures $figure;

    public function getFigure(): Figures
    {
        return $this->figure;
    }
    public function setFigure(Figures $figure): self
    {
        $this->figure = $figure;
        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFigureId(): ?int
    {
        return $this->figure_id;
    }

    public function setFigureId(int $figure_id): static
    {
        $this->figure_id = $figure_id;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    private ?string $plainPassword = null;

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    #[ORM\Column(length: 255)]
    private ?string $Pseudo = null;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column]
    private ?int $UserId = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ResetPasswordToken::class)]
    private Collection $Id;

    public function __construct()
    {
        $this->Id = new ArrayCollection();
    }

    /**
     * @return bool
     */
    public function isIsVerified(): bool
    {
        return $this->is_verified;
    }

    /**
     * @param bool $is_verified
     */
    public function setIsVerified(bool $is_verified): void
    {
        $this->is_verified = $is_verified;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): static
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->UserId;
    }

    public function setUserId(int $UserId): static
    {
        $this->UserId = $UserId;

        return $this;
    }

    public function addId(ResetPasswordToken $id): static
    {
        if (!$this->Id->contains($id)) {
            $this->Id->add($id);
            $id->setUser($this);
        }

        return $this;
    }

    public function removeId(ResetPasswordToken $id): static
    {
        if ($this->Id->removeElement($id)) {
            // set the owning side to null (unless already changed)
            if ($id->getUser() === $this) {
                $id->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/FigureType.php
<?php
// src/Form/FigureType.php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class FigureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('description', TextareaType::class)
            ->add('illustrations', CollectionType::class, [
                'entry_type' => FileType::class,
                'entry_options' => [
                    'required' => false,
                    'label' => 'Illustrations',
                ],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

src/Controller/FiguresController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Figures;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Repository\FiguresRepository;
use App\Entity\Comments;
use App\Form\CommentType;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Group;
use App\Repository\CommentsRepository;

class FiguresController extends AbstractController
{
    #[Route('/figures', name: 'app_figures')]
    public function index(): Response
    {
        return $this->render('figures/index.html.twig', [
            'controller_name' => 'FiguresController',
        ]);
    }

    #[Route('/figure/{slug}', name: 'app_figure_detail')]
public function show(int $id, FiguresRepository $figuresRepository, Request $request, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
{
    $figure = $figuresRepository->findFigureById($slug);

    if (!$figure) {
        throw $this->createNotFoundException('Figure not found');
    }

    // Récupére le nom du groupe correspondant à figure.GroupId
    $groupName = '';
    $group = $entityManager->getRepository(Group::class)->find($figure->getGroupId());
    if ($group) {
        $groupName = $group->getName();
    }

    $comment = new Comments();
    $comment->setFigure($figure);

    $form = $this->createForm(CommentType::class, $comment);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $comment->setCreatedAt(new \DateTimeImmutable());
        $comment->setUser($this->getUser());

        $entityManager->persist($comment);
        $entityManager->flush();

        $this->addFlash('success', 'Votre commentaire a été ajouté.');

        return $this->redirectToRoute('app_figure_detail', ['id' => $figure->getId()]);
    }

    $pagination = $paginator->paginate(
        $figure->getComments(),
        $request->query->getInt('page', 1),
        10
    );

    return $this->render('figures/detail.html.twig', [
        'figure' => $figure,
        'pagination' => $pagination,
        'commentForm' => $form->createView(),
        'groupName' => $groupName, // Transmettre le nom du groupe au modèle Twig
    ]);
}


    #[Route('/ajouter-figure', name: 'ajouter_figure')]
public function addFigure(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
{
    $figure = new Figures();
    $groupRepository = $entityManager->getRepository(Group::class);
    $groups = $groupRepository->findAll();
    $isFormValid = true;

    if ($request->isMethod('POST')) {
        $name = $request->request->get('name');
        $user_id = $request->request->get('user_id');
        $group = $request->request->get("groupId");
        $description = $request->request->get('description');
        $slug = $slugger->slug($name)->lower();

        if (empty($name) || empty($group) || empty($description)) {
            $this->addFlash('danger', 'Veuillez remplir tous les champs.');
            $isFormValid = false;
        }

        // Vérification de l'unicité du nom
        $existingFigure = $entityManager->getRepository(Figures::class)->findOneBy(['name' => $name]);
        if ($existingFigure) {
            $this->addFlash('danger', 'Le nom de la figure existe déjà.');
            $isFormValid = false;
        }

        if ($isFormValid) {
            $figure->setCreatedAt(new \DateTime());
            $figure->setName($name);
            $figure->setDescription($description);
            $figure->setSlug($slug);
            $figure->setGroupId($group);
            $figure->setUserId($user_id);
            $uploadedIllustrationsPaths = [];

            $illustrations = $request->files->get('illustrations');

            // Traitement des images
            if ($illustrations) {
                foreach ($illustrations as $illustration) {
                    if ($illustration instanceof UploadedFile) {
                        $newFilename = $slug . '-' . uniqid() . '.' . $illustration->guessExtension();
                        $illustration->move(
                            $this->getParameter('illustrations_directory'),
                            $newFilename
                        );

                        $uploadedIllustrationsPaths[] = $newFilename;
                    }
                }
            }

            $figure->setIllustrations($uploadedIllustrationsPaths);

            // Traitement des vidéos
            $videos = $request->request->get('videos');
            $figure->setMovie($videos);
            $entityManager->persist($figure);
            $entityManager->flush();

            $this->addFlash('success', 'La figure a été ajoutée avec succès.');

            return $this->redirectToRoute('app_default');
        }
    }

    return $this->render('figures/add_figure.html.twig',['groups' => $groups,]);
}


    #[Route('/modifier-figure/{id}', name: 'modifier_figure')]
public function editFigure(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger, $id): Response
{
    $figureRepository = $entityManager->getRepository(Figures::class);
    $figure = $figureRepository->find($id);

    // Vérifiez si la figure existe
    if (!$figure) {
        throw $this->createNotFoundException('La figure n\'existe pas');
    }

    // Vous pouvez maintenant utiliser $figure pour pré-remplir le formulaire de modification.

    $groupRepository = $entityManager->getRepository(Group::class);
    $groups = $groupRepository->findAll();

    if ($request->isMethod('POST')) {
        // Traitez les données du formulaire de modification ici, en utilisant $figure pour mettre à jour les valeurs existantes.

        $name = $request->request->get('name');
        $group = $request->request->get("groupId");
        $description = $request->request->get('description');
        $slug = $slugger->slug($name)->lower();

        $figure->setName($name);
        $figure->setDescription($description);
        $figure->setSlug($slug);
        $figure->setGroupId($group);

        // Traitement des illustrations
        $anciennesIllustrations = $figure->getIllustrations();
        $uploadedIllustrationsPaths = [];

        $illustrations = $request->files->get('illustrations');

        if ($illustrations) {
            foreach ($illustrations as $illustration) {
                if ($illustration instanceof UploadedFile) {
                    $newFilename = $slug . '-' . uniqid() . '.' . $illustration->guessExtension();
                    $illustration->move(
                        $this->getParameter('illustrations_directory'),
                        $newFilename
                    );

                    $uploadedIllustrationsPaths[] = $newFilename;
                }
            }
        }

        $illustrations = array_merge($anciennesIllustrations, $uploadedIllustrationsPaths);
        $figure->setIllustrations($illustrations);
        // Traitement des vidéos
        $videos = $request->request->get('videos');
        $figure->setMovie($videos);

        $entityManager->flush();

        $this->addFlash('success', 'La figure a été modifiée avec succès.');

        return $this->redirectToRoute('app_default');
    }

    return $this->render('figures/edit_figure.html.twig', ['groups' => $groups, 'figure' => $figure]);
}

#[Route('/figure/supprimer/{id}', name: 'supprimer_figure')]
    public function supprimerFigure(int $id, FiguresRepository $figuresRepository, CommentsRepository $commentsRepository, EntityManagerInterface $entityManager): Response
    {
        // Récupérez la figure à supprimer en utilisant le repository
        $figure = $figuresRepository->find($id);

        if (!$figure) {
            throw $this->createNotFoundException('Figure not found');
        }

        // Récupérez tous les commentaires associés à cette figure
        $comments = $commentsRepository->findBy(['figure' => $figure]);

        // Supprimez d'abord les commentaires associés
        foreach ($comments as $comment) {
            $entityManager->remove($comment);
        }

        // Supprimez ensuite la figure elle-même
        $entityManager->remove($figure);
        $entityManager->flush();

        // Ajoutez un message flash pour indiquer que la figure et les commentaires ont été supprimés avec succès
        $this->addFlash('success', 'La figure et ses commentaires ont été supprimés avec succès.');

        // Redirigez l'utilisateur vers une page appropriée (par exemple, la liste des figures)
        return $this->redirectToRoute('app_default');
    }
}

templates/figures/add_figure.html.twig
{% extends 'base.html.twig' %}

{% block title %}SnowFlow{% endblock %}

{% block body %}
{% for flashMessage in app.flashes('success') %}
    <div class="alert alert-success">
        {{ flashMessage }}
    </div>
{% endfor %}

{% for flashMessage in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ flashMessage }}
    </div>
{% endfor %}
<div class="container" style="margin-top: 200px;">
 <form action="{{ path('ajouter_figure') }}" enctype="multipart/form-data" method="post">
        <div class="form-group">
            <label for="name">Nom</label>
            <input type="text" id="name" name="name" class="form-control">
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" name="description" class="form-control"></textarea>
        </div>

        <div class="form-group">
    <label for="group">Groupe de figure</label>
    <select id="groupId" name="groupId" value="groupId" class="form-control">
        <option value="">Sélectionnez un groupe</option>
        {% for group in groups %}
            <option value="{{ group.id }}" name="groupId">{{ group.name }}</option>
        {% endfor %}
    </select>
    <input type="hidden" id="user_id" name="user_id" value="">
</div>

        <div class="form-group">
            <label for="illustrations">Illustrations</label>
            <input type="file" id="illustrations" name="illustrations[]" multiple>
        </div>


        <div class="form-group">
            <label for="videos">Liens de vidéos</label>
            <div id="videos-container">
                <input type="text" id="videos" name="videos" class="form-control mb-2">
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </div>
    </form>
</div>
    <script>
    var userId = {{ app.user ? app.user.id : 0 }};
    document.getElementById('user_id').value = userId;
</script>
{% endblock %}

templates/figures/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ figure.name }}{% endblock %}

{% block body %}
{% for flashMessage in app.flashes('success') %}
    <div class="alert alert-success">
        {{ flashMessage }}
    </div>
{% endfor %}

{% for flashMessage in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ flashMessage }}
    </div>
{% endfor %}
<div class="text-end p-4" style="margin-top:200px">
                        {% if app.user and app.user.id == figure.userId %}
                             <a href="{{ path('modifier_figure', {'id': figure.id}) }}" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-pen"></i></a>
                                  <a href="{{ path('supprimer_figure', {'id': figure.id}) }}" class="btn btn-sm btn-outline-secondary">
    <i class="fa-solid fa-trash"></i>
</a>
                        {% endif %}
                    </div>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="banner">
                    <img src="{{ asset('uploads/figures/' ~ figure.illustrations[0]) }}" alt="Bannière" class="img-fluid">
                    <h1 class="banner-title bg-white fw-bold text-align-center">{{ figure.name }}</h1>
                </div>

<div class="row mt-4 ">
                    <div class="col">
                        <div class="image-gallery d-flex flex-row align-items-end">
    {% for illustration in figure.illustrations %}
        <a href="{{ asset('uploads/figures/' ~ illustration) }}" data-fancybox="gallery">
            <img src="{{ asset('uploads/figures/' ~ illustration) }}" alt="Illustration" class="img-thumbnail m-2" width="150" height="150">
        </a>
    {% endfor %}
    
    {% if figure.movie is defined and figure.movie|length > 0 %}
        <a href="{{ figure.movie }}" data-fancybox="gallery">
            <iframe width="150" height="150" src="{{ figure.movie }}" frameborder="0" allowfullscreen></iframe>
        </a>
    {% endif %}
</div>
                    </div>
                    </div>
                <div class="row mt-4">
                    <div class="col">
                        <h2>Description</h2>
                        <p>{{ figure.description }}</p>
                    </div>
                
                </div>
                </div>
<div class="row mt-4 " style="place-content: center;">
                    <div class="col-5 text-center">
               <span class="badge text-bg-primary">dernière modification : {{ figure.createdAt|date('d/m/Y H:i') }}</span>

                    </div> 
                    <div class="col-5 text-center">
<span class="badge text-bg-secondary">{{ groupName }}</span>
                    </div> 
                </div>
                </div>
                <div class="row mt-4">
                    <div class="col">
                        {% if app.user %}
                            <h2>Laisser un commentaire</h2>
                            {{ form_start(commentForm) }}
                            {{ form_row(commentForm.content, { 'attr': {'class': 'form-control'} }) }}
                            <button type="submit" class="btn btn-primary mt-2">Ajouter le commentaire</button>
                            {{ form_end(commentForm) }}
                        {% endif %}
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="col-md-8">
                        <h2>Commentaires</h2>
                        {% for comment in pagination %}
                            <div class="comment mb-4">
                                <div class="d-flex align-items-center">
                                    {% if comment.user.image %}
                                        <img src="{{ asset(comment.user.image) }}" alt="{{ comment.user.pseudo }}" class="profile-image me-2 img-thumbnail" width="50" height="50">
                                    {% else %}
                                        <i class="fa-solid fa-user profile-icon me-2"></i>
                                    {% endif %}
                                    <span>{{ comment.user.pseudo }}</span>
                                </div>
                                <div class="comment-content">
                                    <p>{{ comment.content }}</p>
                                </div>
                                <div class="comment-date">
                                    <i class="fa-solid fa-clock me-1"></i>
                                    {{ comment.createdAt|date('d/m/Y H:i') }}
                                </div>
                            </div>
                            {% if not loop.last %}
                                <hr class="my-4">
                            {% endif %}
                        {% endfor %}
                        <div class="mt-4">
                            {{ knp_pagination_render(pagination) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
{% endblock %}

templates/figures/edit_figure.html.twig
{% extends 'base.html.twig' %}

{% block title %}SnowFlow{% endblock %}

{% block body %}
<div class="container" style="margin-top: 200px;">
<div class="container" style="margin-top: 200px;">
   <form action="{{ path('modifier_figure', {'id': figure.id}) }}" enctype="multipart/form-data" method="post">

        <div class="form-group">
            <label for="name">Nom</label>
            <input type="text" id="name" name="name" class="form-control" value="{{ figure.name }}">
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" name="description" class="form-control">{{ figure.description }}</textarea>
        </div>

        <div class="form-group">
    <label for="group">Groupe de figure</label>
    <select id="groupId" name="groupId" class="form-control">
        <option value="">Sélectionnez un groupe</option>
        {% for group in groups %}
            <option value="{{ group.id }}" {% if group.id == figure.GroupId %}selected{% endif %}>{{ group.name }}</option>
        {% endfor %}
    </select>
</div>

        <div class="form-group">
            <label for="illustrations">Illustrations</label>
            <input type="file" id="illustrations" name="illustrations[]" multiple>
        </div>

        <div class="form-group">
            <label for="videos">Liens de vidéos</label>
            <div id="videos-container">
                <input type="text" id="videos" name="videos" class="form-control mb-2">
            </div>
            <button type="button" class="btn btn-secondary" id="add-video">Ajouter un lien</button>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Modifier</button>
        </div>
    </form>
    <div class="container">
    <div class="row">
        {% for illustration in figure.illustrations %}
            <div class="col-md-4">
                <div class="card mb-3">
                    <img src="{{ asset('uploads/figures/' ~ illustration) }}" class="card-img-top" alt="Illustration">
                </div>
            </div>
            {% if loop.index % 3 == 0 %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}