src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    private ?string $plainPassword = null;

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    #[ORM\Column(length: 255)]
    private ?string $Pseudo = null;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column]
    private ?int $UserId = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ResetPasswordToken::class)]
    private Collection $Id;

    public function __construct()
    {
        $this->Id = new ArrayCollection();
    }

    /**
     * @return bool
     */
    public function isIsVerified(): bool
    {
        return $this->is_verified;
    }

    /**
     * @param bool $is_verified
     */
    public function setIsVerified(bool $is_verified): void
    {
        $this->is_verified = $is_verified;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): static
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->UserId;
    }

    public function setUserId(int $UserId): static
    {
        $this->UserId = $UserId;

        return $this;
    }

    public function addId(ResetPasswordToken $id): static
    {
        if (!$this->Id->contains($id)) {
            $this->Id->add($id);
            $id->setUser($this);
        }

        return $this;
    }

    public function removeId(ResetPasswordToken $id): static
    {
        if ($this->Id->removeElement($id)) {
            // set the owning side to null (unless already changed)
            if ($id->getUser() === $this) {
                $id->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}SnowTricks{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" />

        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <style>
    .banner {
    position: relative;
}

.banner-title {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: rgba(0, 0, 0, 0.7);
    padding: 10px 20px;
    border-radius: 5px;
}
    </style>
    <body>
    <div class="container">
        <header style="background-color: white" class=" lh-1 py-3 fixed-top">
            <div class="row flex-nowrap justify-content-between align-items-center mr-1">
                <div class="col-4 pt-1">
                    <a class="link-secondary" href="{{ path('app_default') }}">
                        <img class="w-25" src="https://zupimages.net/up/23/34/tog8.png" alt="Logo SnowFlow">
                    </a>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    {% if app.user %}
                        <div class="mr-3">
                            <span style="margin-right: 10px;" class="mr-1">Bonjour, {{ app.user.pseudo }}</span>
                        </div>
                        <div class="mr-3">
                            <a style="margin-right: 10px;" class="btn btn-sm btn-outline-secondary mr-1" href="{{ path('app_user_edit') }}" title="modifier le profil"><i class="fa-solid fa-address-card"></i></a>
                        </div>

                        <div class="mr-3">
                            <a style="margin-right: 10px;" class="btn btn-sm btn-outline-secondary mr-1" href="{{ path('ajouter_figure') }}" title="ajouter une figure"><i class="fa-solid fa-pen"></i></a>
                        </div>
                        <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_logout') }}">Déconnexion</a>
                    {% else %}
                        <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_login') }}">Connexion</a>
                    {% endif %}
                </div>
            </div>
        </header>
        {% if app.user and app.user.isVerified == false %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                <div class="alert-message">
                    <strong>Votre compte n'est pas activé</strong>, <a href="#">renvoyer le lien d'activation</a>
                </div>
            </div>
        {% endif %}
    </div>

    {% block body %}{% endblock %}
    </body>

    <footer class="py-5 text-center text-body-secondary bg-body-tertiary">
        <p class="mb-0">
            <a href="#"><i class="fa-solid fa-arrow-up" style="background: none ; border:none;"></i></a>
        </p>
    </footer>
</html>